services:
  backend:
    image: pill-taker-backend
    container_name: pill-taker-backend
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env.development
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  frontend:
    image: pill-taker-frontend
    container_name: pill-taker-frontend
    build:
      context: ../frontend
      dockerfile: dockerfile
    ports:
      - 80:80
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: pill-taker-postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
    name: pill-taker-pgdata

networks:
  default:
    name: pill-taker
